channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - ipywidgets
  - ipyleaflet
  - numba
  - pandas
  - requests
  - numpy
  - rasterio
  - tqdm
  - affine
  - scipy
  - Pillow
  - matplotlib
  - ipywidgets
  - xarray
  - pyproj
  - branca
  - pydap
  - dask
  - distributed
  - bokeh
  - nbserverproxy
  - jupyter
  - jupyterlab
  - lxml
  - zarr
  - intake
  - intake-xarray
  - graphviz
  - dask-kubernetes
  - scikit-image
  - shapely
  - tornado=5.1.1
  - python-wget
  - pip
  - pip:
    - dask_labextension
    - soupsieve
    - gcsfs
